### ISSUE TITLE
`peek_key` function was lost

### ISSUE THREAD

**Issue by Jovvik** [mpdn/radix-heap#8]
It seems you lost some commits when merging #6, see attached diagram (blue is master).
![image](https://user-images.githubusercontent.com/31628566/154546115-48c21c49-db28-4306-a36b-a24b97897b31.png)

Could you add them back? I am specifically interested in ff0ef3f3cb853d4c0d80dc409617d75c145af696, since it adds `peek_key`.

**Comment by Jovvik** [comment]
After reading the source code, I see `peek_key` needs running max in buckets, which is now removed. Could `peek_key` perhaps be implemented behind a feature flag that would enable running max?

**Comment by mpdn** [comment]
Oops - that was indeed a mistake.

But yeah, as you write it requires running max in buckets which I removed after some benchmarking revealed it to not be beneficial. You can sort of do `peek_key` by first calling `constrain` and then getting the next key via `top`. This will require mutating the heap though, and also move the top value, but would that work in your case?

**Comment by Jovvik** [comment]
Yes, that works in my case, thank you. Just for the record, it is faster than popping and pushing back the popped value

**Comment by nirvana-msu** [comment]
It would still be great to get support for key peeking (without resetting `top`), e.g, behind an optional feature flag if it affects performance.

The workaround with calling `constrain` is not always suitable as it can conflict with monotonicity requirement. Imagine I have an event queue which is naturally monotonic - say, I just push events to be triggered at certain times in the future, and gradually consume them as time goes by. It is monotonic because I never need to push an event which is in the past - however if I call `constrain` and thus bump `top` key to a future timestamp, I can no longer push any event that would need to trigger between now and this future timestamp. Sometimes this is not a big deal and you can cap(/floor) the keys of new events, but sometimes this is not acceptable.

**Comment by nirvana-msu** [comment]
Just to note again that nearly every time I find myself reaching out for a monotonic heap, I also need the `peek`, and usually the workaround with calling `constrain` is not suitable as it moves the top value (and you don't want it moved unless you end up popping). It is a real shame this functionality was removed - whatever performance impact it had couldn't have been worse than popping and pushing a value back... 

There must be a way to implement this with minimal performance impact for the case where `peek` is not used, or perhaps even put it behind an opt-in feature flag,,. it would make a big difference!

**Comment by Fuuzetsu** [comment]
We have a use-case which is basically identical to the comment above: we have timestamps and we maintain an in variant that a `push` is never going to go back in time from the last `pop`: perfect for the radix heap. But we do also want to see what the next element on the heap would be but do _not_ want to pop off/set new `top`: we may still queue some timestamps in front of it, depending on the peek...

**Comment by Fuuzetsu** [comment]
I should add that in our case, we would also like to `peek` the value... but at least the key is something.
